apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ixhvw0y4r-python
  janus-idp.io/tekton: ixhvw0y4r-python
  backstage.io/kubernetes-id: ixhvw0y4r-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ixhvw0y4r-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
